# Generated by Django 4.2.29 on 2026-03-06 03:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stgvendas',
            new_name='relatorios__data_fa_ee7e5c_idx',
            old_name='relatorios_data_fa_idx',
        ),
        migrations.RenameIndex(
            model_name='stgvendas',
            new_name='relatorios__data_fa_060871_idx',
            old_name='relatorios_data_fa_supervi_idx',
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='pesoliq',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='qtdevol',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='valorbonificado',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stgvendas',
            name='vldevolucao',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=16, null=True),
        ),
    ]
