# Generated by Django 4.2.29 on 2026-03-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_rename_relatorios_data_fa_idx_relatorios__data_fa_ee7e5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgvendas',
            name='fornecedor',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
