# Generated by Django 4.2.29 on 2026-03-07 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0005_traduzir_permissoes_auth_pt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stgvendas',
            options={'permissions': [('pode_ver_relatorio_vendas', 'Pode ver relatório de vendas'), ('pode_exportar_excel', 'Pode exportar Excel'), ('pode_ver_todas_filiais', 'Pode ver todas as filiais'), ('pode_ver_power_bi', 'Pode ver Dashboard Power BI')], 'verbose_name': 'Staging Venda', 'verbose_name_plural': 'Staging Vendas'},
        ),
        migrations.CreateModel(
            name='RecursoPBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL do relatório (embed)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('usuarios_permitidos', models.ManyToManyField(blank=True, help_text='Usuários que podem ver este link no Dashboard PBI. Deixe vazio para nenhum usuário.', related_name='recursos_pbi', to=settings.AUTH_USER_MODEL, verbose_name='Usuários com acesso')),
            ],
            options={
                'verbose_name': 'Recurso PBI (link)',
                'verbose_name_plural': 'Recursos PBI (links)',
                'ordering': ('ordem', 'nome'),
            },
        ),
    ]
