# Generated by Django (add cliente_formatado for display from CSV column CLIENTE_FORMATADO)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0008_add_codcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgvendas',
            name='cliente_formatado',
            field=models.CharField(blank=True, max_length=250, verbose_name='Cliente formatado (CodCli - Nome)'),
        ),
    ]
